### ISSUE TITLE
Finalize content and formatting of Data Curation section

### ISSUE THREAD

**Issue by LuciMoore** [DCAN-Labs/hbcd-docs#10]
@cmadjar  to finalize initial [draft md conversion from google doc](https://github.com/DCAN-Labs/hbcd-docs/blob/datacuration/docs/bidscuration.md) in datacuration branch and submit PR

**Comment by LuciMoore** [comment]
@cmadjar I took the liberty of doing some minor formatting cleanup in order to merge the current content with main

**Comment by LuciMoore** [comment]
@cmadjar I also created a branch specific for updates to this section that you can use instead of dev https://github.com/DCAN-Labs/hbcd-docs/tree/datacuration

**Comment by cmadjar** [comment]
Wow! Thank you!! :-)

Will update once the google doc is finalized. It is still a WIP.

**Comment by LuciMoore** [comment]
sounds good! the format/organization may evolve quite a bit (I only put the webpage recently, so I'm still reworking some larger aspects of it), so just reach out on slack if you want to touch base first once you're ready to update the content!

**Comment by LuciMoore** [comment]
@cmadjar I think I've got this covered actually, so will delete the [datacuration branch](https://github.com/DCAN-Labs/hbcd-docs/tree/datacuration) branch for now. Please let me know when the EEG section content is somewhat stable and I'll go ahead and add that content
